/* Generated By:JJTree&JavaCC: Do not edit this line. DomainTreeConstants.java */
package drctree;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DomainTreeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LEFTBRACE = 5;
  /** RegularExpression Id. */
  int RIGHTBRACE = 6;
  /** RegularExpression Id. */
  int LEFTSQUARE = 7;
  /** RegularExpression Id. */
  int RIGHTSQUARE = 8;
  /** RegularExpression Id. */
  int SEPERATOR = 9;
  /** RegularExpression Id. */
  int NOT = 10;
  /** RegularExpression Id. */
  int EXIST = 11;
  /** RegularExpression Id. */
  int FORALL = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int OR = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;
  /** RegularExpression Id. */
  int ALIAS = 16;
  /** RegularExpression Id. */
  int WORD = 17;
  /** RegularExpression Id. */
  int CONSTRAIN = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int LETTER = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "\"\\u00ac\"",
    "\"\\u2203\"",
    "\"\\u2200\"",
    "\"\\u039b\"",
    "\"\\u2228\"",
    "<NUMBER>",
    "<ALIAS>",
    "<WORD>",
    "<CONSTRAIN>",
    "<DIGIT>",
    "<LETTER>",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"<>\"",
  };

}
