/* Generated By:JavaCC: Do not edit this line. DomainTreeTreeConstants.java Version 5.0 */
package drctree;

public interface DomainTreeTreeConstants
{
  public int JJTSTART = 0;
  public int JJTONE_LINE = 1;
  public int JJTEXPR = 2;
  public int JJTRES = 3;
  public int JJTSUB = 4;
  public int JJTCONJ = 5;
  public int JJTTERM = 6;
  public int JJTVARLIST = 7;
  public int JJTVAR = 8;
  public int JJTTAB = 9;
  public int JJTCOND = 10;


  public String[] jjtNodeName = {
    "Start",
    "one_line",
    "EXPR",
    "RES",
    "SUB",
    "CONJ",
    "TERM",
    "VARLIST",
    "VAR",
    "TAB",
    "COND",
  };
}
/* JavaCC - OriginalChecksum=59432c0c461bf8fe3d070de129a97e88 (do not edit this line) */
