/* Generated By:JJTree&JavaCC: Do not edit this line. RATreeConstants.java */
package ratree;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RATreeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROJECT = 5;
  /** RegularExpression Id. */
  int SELECT = 6;
  /** RegularExpression Id. */
  int UNION = 7;
  /** RegularExpression Id. */
  int INTERSECT = 8;
  /** RegularExpression Id. */
  int RENAME = 9;
  /** RegularExpression Id. */
  int JOIN = 10;
  /** RegularExpression Id. */
  int CARTESIAN = 11;
  /** RegularExpression Id. */
  int DIFFERENCE = 12;
  /** RegularExpression Id. */
  int ASSIGN = 13;
  /** RegularExpression Id. */
  int COMPARE = 14;
  /** RegularExpression Id. */
  int AND = 15;
  /** RegularExpression Id. */
  int OR = 16;
  /** RegularExpression Id. */
  int NUMBER = 17;
  /** RegularExpression Id. */
  int WORD = 18;
  /** RegularExpression Id. */
  int CONSTRAIN = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
  /** RegularExpression Id. */
  int LETTER = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\u03c0\"",
    "\"\\u03c3\"",
    "\"\\u222a\"",
    "\"\\u2229\"",
    "\"\\u03c1\"",
    "\"\\u22c8\"",
    "\"\\u00d7\"",
    "\"-\"",
    "\"\\u2190\"",
    "<COMPARE>",
    "\"\\u039b\"",
    "\"\\u2228\"",
    "<NUMBER>",
    "<WORD>",
    "<CONSTRAIN>",
    "<DIGIT>",
    "<LETTER>",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
  };

}
