/* Generated By:JavaCC: Do not edit this line. RATreeTreeConstants.java Version 5.0 */
package ratree;

public interface RATreeTreeConstants
{
  public int JJTSTART = 0;
  public int JJTONE_LINE = 1;
  public int JJTEXPR = 2;
  public int JJTASSIGN = 3;
  public int JJTSETOP = 4;
  public int JJTRENAME = 5;
  public int JJTSEL = 6;
  public int JJTPROJ = 7;
  public int JJTRELA = 8;
  public int JJTATTR = 9;
  public int JJTATTRLIST = 10;
  public int JJTOPER = 11;
  public int JJTCOND = 12;
  public int JJTCONDS = 13;
  public int JJTANDOR = 14;


  public String[] jjtNodeName = {
    "Start",
    "one_line",
    "EXPR",
    "ASSIGN",
    "SETOP",
    "RENAME",
    "SEL",
    "PROJ",
    "RELA",
    "ATTR",
    "ATTRLIST",
    "OPER",
    "COND",
    "CONDS",
    "ANDOR",
  };
}
/* JavaCC - OriginalChecksum=73afaa98a5e44678ab66759c9c0d0d36 (do not edit this line) */
