/* Generated By:JavaCC: Do not edit this line. TupleTreeTreeConstants.java Version 5.0 */
package trctree;

public interface TupleTreeTreeConstants
{
  public int JJTSTART = 0;
  public int JJTONE_LINE = 1;
  public int JJTEXPR = 2;
  public int JJTRES = 3;
  public int JJTSUB = 4;
  public int JJTCONJ = 5;
  public int JJTTERM = 6;
  public int JJTVAR = 7;
  public int JJTLIST = 8;
  public int JJTTAB = 9;
  public int JJTCOND = 10;


  public String[] jjtNodeName = {
    "Start",
    "one_line",
    "EXPR",
    "RES",
    "SUB",
    "CONJ",
    "TERM",
    "VAR",
    "LIST",
    "TAB",
    "COND",
  };
}
/* JavaCC - OriginalChecksum=22a909b0e0c550843d9ff5337a9b2f6f (do not edit this line) */
